// 规定 各种事件的状态  方法常量值，统一处理在这里，一般都是业务字符串常量。


// 用户相关的操作
// 登录
export const SETTOKEN = 'SETTOKEN';
export const UPDATETOKEN = 'UPDATETOKEN';
export const DELETETOKEN = 'DELETETOKEN';



// 增加
export const INCREMENT = 'INCREMENT';
// 减少
export const DECREMENT = 'DECREMENT';

// 请求之前加载动画
export const SHOWLOAGING = 'SHOWLOAGING';

export const HIDELOADING = 'HIDELOADING';

// 用户信息
// 更新用户信息
export const UPDATEUSERINFO = 'UPDATEUSERINFO';
export const GETUSERINFO = 'GETUSERINFO';
export const CLEARUSERINFO = 'CLEARUSERINFO';


// 用户自定义资源 
export const SETUSERORIFILElIST = "SETUSERORIFILElIST";
export const GETUSERORIFILElIST = "GETUSERORIFILElIST";

export const SETUSERORIFILEDETAIL = "SETUSERORIFILEDETAIL";
export const GETUSERORIFILEDETAIL = "GETUSERORIFILEDETAIL";

export const DELETEUSERORIFILE = "DELETEUSERORIFILE";


// 用户原创
// 保存
 export const STOREUSERORITMP = "STOREUSERORITMP"
 export const UPDATEUSERORITMP = "UPDATEUSERORITMP"
 export const GETUSERORITMPLIST = "GETUSERORITMPLIST"
 export const SETUSERORITMPLIST = "SETUSERORITMPLIST"
 export const DELETEUSERORITMP = "DELETEUSERORITMP"
 export const USERORIDETAIL = "USERORIDETAIL"

//  用户权限
export const USERPREMISSIONLIST = "USERPREMISSIONLIST"
export const ADDUSERPREMISSION = "ADDUSERPREMISSION"
export const UPDATEUSERPREMISSION = "UPDATEUSERPREMISSION"
export const USERPREMISSIONDETAIL = "USERPREMISSIONDETAIL"

// 用户角色
export const USERROLELIST = "USERROLELIST"
export const ADDUSERROLE = "ADDUSERROLE"
export const USERROLEDETAIL = "USERROLEDETAIL"
export const UPDATEUSERROLE = "UPDATEUSERROLE"
export const USERROLEPREMISSIONS = "USERROLEPREMISSIONS"
export const STOREUSERROLEPREMISSION = "STOREUSERROLEPREMISSION"

//用户
export const USERLIST = "USERLIST"
export const USERSROLES = "USERSROLES"
export const USERSTOREROLES = "USERSTOREROLES"


//目录
export const MENULIST = "MENULIST"
export const DELETEMENUITEM = "DELETEMENUITEM"
export const UPDATEMENUITEM = "UPDATEMENUITEM"
export const STOREMENUITEM = "STOREMENUITEM"
export const APPMENU = "APPMENU"

// 权限资源配置
export const PREMISSIONRESOURCES = "PREMISSIONRESOURCES"
export const STOREPREMISSIONRESOURCES = "STOREPREMISSIONRESOURCES"




